superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include ('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/')),
    
    
    

]

superhero_project/superheroes/urls.py
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name = 'create' )
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name
        

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from.models import Superhero


# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    details = Superhero.objects.get(pk= all)

    context = {
        'single_hero': single_hero,
        'details': details
            
    }
    return render (request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        #save form contents to database
        #return to index
        name = request.POST.get('name')
        alter_ego  = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catch_phrase = request.POST.get('catch_phrase')
        new_hero = Superhero(name = name, alter_ego = alter_ego, primary_ability = primary_ability, secondary_ability = secondary_ability, catch_phrase = catch_phrase )
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')   

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action = "{% url 'superheroes:create' %}" method = "post">
        {% csrf_token %}
        Name: <input type = "text" name = "name" id = "name"> <br/>
        Alter Ego: <input type = "text" name = "alter_ego" id = "alter_ego"> <br/>
        Primary Ability: <input type = "text" name = "primary_ability" id = "primary_ability"> <br/>
        Secondary Ability: <input type = "text" name = "secondary_ability" id = "secondary_ability"> <br/>
        Catchphrase: <input type = "text" name = "catch_phrase" id = "catch_phrase"> <br/>
        <input type = "submit" value = "Add!">
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Details</title>
</head>
<body>
    <h1>Details...</h1>
    <ul>
        {% for detail in details %}
            detail += range(1, len(Superhero.objects.get(all)))
        <li><h2>{{ % hero.name % }}</h2></li>
      
    </ul>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heroes...</h1>
    <ul>
        {%for hero in all_heroes %}
        <li><h2>{{hero.name}}</h2></li>
        {% endfor%}    

    </ul>
    <a href = "{% url 'superheroes:create' %}">Add New Hero</a>
</body>
</html>